- apt_repository:
    repo: "ppa:fish-shell/release-3"

- name: "update apt"
  become: yes
  apt: update_cache=yes

- name: "install"
  become: yes
  apt:
    pkg:
      - fish
    state: latest

- name: "Retrieve Facts"
  command: "fish -c echo 'Hello'"

- name: "Creates conf directory"
  file:
    path: "{{dotfiles_user_home}}/.config/fish/conf.d"
    state: directory
    owner: rryter
    group: rryter
    mode: 0775

- name: "Copy custom fish files."
  copy:
    src: fish/fishfile
    dest: "{{dotfiles_user_home}}/.config/fish/fishfile"
    owner: rryter
    group: rryter
    mode: "0744"

- name: "Copy custom fish files."
  copy:
    src: fish/config.fish
    dest: "{{dotfiles_user_home}}/.config/fish/config.fish"
    owner: rryter
    group: rryter
    mode: "0744"

- name: "Copy custom fish files."
  copy:
    src: fish/conf.d/gpg-agent.fish
    dest: "{{dotfiles_user_home}}/.config/fish/conf.d/gpg-agent.fish"
    owner: rryter
    group: rryter
    mode: "0744"
