- apt_repository:
    repo: "ppa:fish-shell/release-3"

- name: "[Fish] update apt"
  become: yes
  apt: update_cache=yes

- name: "[Fish] install"
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - fish

- name: "[Fish] Copy custom fish files."
  synchronize:
    src: templates
    dest: "{{dotfiles_user_home}}/.config/fish"
    dirs: yes
