---
- hosts:
    - ibm

  become: yes
  vars:
    dotfiles_user_home: "/home/rryter"
    proxy:
      addr: localhost
      port: 5050
  roles:
    - system
    - git
    - fish
    - cypress
    - chrome
    - pgkehle.proxy-setup
