---
# the host in which the playbook will be run
- hosts:
    - ibm

  become: yes
  # the target user Ansible will impersonate when provisioning
  vars:
    dotfiles_user_home: "/root"
    proxy:
      addr: localhost
      port: 1337
  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - system
    #- oefenweb.yarn
    - pgkehle.proxy-setup
    - role: moviedo.nvm
      nvm_user: "{{ ansible_user }}"
      nvm_working_path: "{{ dotfiles_user_home }}"
    - git
    - npm
    - cypress
    - chrome
    - fish
  # environment:
  #   http_proxy: http://192.168.0.169:3128
  #   https_proxy: http://192.168.0.169:3128
