---
# the host in which the playbook will be run
- hosts: localhost
  # in this example, we using a localhost, so this is needed
  connection: local

  # the target user Ansible will impersonate when provisioning
  user: rryter

  # this makes all tasks run with sudo by default
  become: yes

  vars:
    dotfiles_user_home: "/home/rryter"
    proxy:
      addr: 192.168.0.169
      port: 3128
  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - system
    - oefenweb.yarn
    - pgkehle.proxy-setup
    - role: moviedo.nvm
      nvm_user: rryter
    - git
    - npm
    - cypress
    - chrome
    - zsh
  # environment:
  #   http_proxy: http://192.168.0.169:3128
  #   https_proxy: http://192.168.0.169:3128
