---
# the host in which the playbook will be run
- hosts:
    - ibm

  become: yes
  # the target user Ansible will impersonate when provisioning
  vars:
    dotfiles_user_home: "/home/rryter"
    proxy:
      addr: localhost
      port: 3128
  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - system
    - pgkehle.proxy-setup
    #- role: moviedo.nvm
    #  nvm_user: "{{ ansible_user }}"
    #  nvm_working_path: "{{ dotfiles_user_home }}"
    - git
    - npm
    - cypress
    - chrome
    - fish
