- name: "Install Dependencies"
  # apt is our module. It installs debian packages. Here we are passing an
  # `` variable, which is the item from `with_items`
  apt: pkg=
  # `with_items` will loop through a list and run the module passing each item
  # as ``
  with_items:
    - libgtk2.0-0
    - libgtk-3-0
    - libnotify-dev
    - libgconf-2-4
    - libnss3
    - libxss1
    - libasound2
    - libxtst6
    - xauth
    - xvfb
