- name: "[ZSH] Retrieve Facts"
  shell: "echo $SHELL"
  register: default_shell
  changed_when: False
  sudo: no

# Now, we want to set zsh as the default shell, unless it is already the default
# one.
- name: "[ZSH] Set ZSH as the default shell"
  shell: chsh -s /bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1
